---
title: 'Tutorial: RAxML'
output:
  html_document: default
  word_document: default
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8, eval = FALSE,
                      echo=TRUE, warning=FALSE, message=FALSE,
                      tidy = TRUE, collapse = TRUE,
                      results = 'hold')
```
\
\

### Timings 
  1. Run RAxML (ca. 1 hour for 10 bootstraps)
  
All done in EVE cluster

\
\

### 1. Run RAxML
#This is all done in the EVE cluster, it will take some time - we can reduce the number of bootstrap replicates...

```{r}
### RAxML
#!/bin/bash                                                                                                                            

#SBATCH --job-name=RAxML
#SBATCH --mail-user=christopher_david.barratt@uni-leipzig.de
#SBATCH --mail-type=BEGIN,END,FAIL,TIME_LIMIT
#SBATCH --chdir /data/barratt  
#SBATCH --output=/work/barratt/Workshop_3/job_logs/%x-%j.log
#SBATCH --cpus-per-task=1 
#SBATCH --mem-per-cpu=20G
#SBATCH --time=12:00:00

#load environment
module purge 
module load GCC/10.2.0
module load OpenMPI/4.0.5
module load RAxML/8.2.12-hybrid-avx2

cd ~/work/Workshop_3/Leptopelis_flavomaculatus/Inputs/RAxML/

# 100 bootstraps
raxmlHPC -f a -m GTRCAT -p 12345 -x 12345 -# 100 -s  ~/work/Workshop_3/Leptopelis_flavomaculatus/Inputs/RAxML/Lflavomaculatus.phy ­­asc­corr=lewis -n bootstrapped 
raxmlHPC -m GTRCAT -p 12345 -f b -t RAxML_bestTree.bootstrapped -z RAxML_bootstrap.bootstrapped -n FINAL_bootstrapped.tre

```

